[profile.default]
src = 'src'
out = 'out'
libs = ['vendor']
solc = '0.8.24'
optimizer = true
optimizer_runs = 200

auto_detect_remappings = true
ignored_paths = [
    'lib/**/test/**',
    'lib/**/certora/**'
]
remappings = [
  'forge-std/=vendor/forge-std/src/',
  'ds-test/=vendor/forge-std/lib/ds-test/src/',
  'openzeppelin-contracts/=vendor/openzeppelin-contracts/contracts/',
  'solmate/=vendor/solmate/src/'
]

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

[profile.default.rpc_endpoints]
xlayer_testnet = 'https://xlayertestrpc.okx.com'
